/**
 * Production Environment Constants - Phase 15A
 * DRY compliance: Centralized production configuration
 */

export const PRODUCTION_LIMITS = {
  RATE_LIMIT_WINDOW_MS: 60000, // 1 minute
  RATE_LIMIT_MAX_REQUESTS: 100,
  MAX_TOOL_EXECUTION_TIME_MS: 30000, // 30 seconds
  MAX_CIRCUIT_BREAKER_FAILURES: 5,
  CIRCUIT_BREAKER_RESET_TIME_MS: 60000, // 1 minute
  MAX_RETRY_ATTEMPTS: 3,
  METRICS_RETENTION_MS: 24 * 60 * 60 * 1000, // 24 hours
  HEALTH_CHECK_INTERVAL_MS: 30000 // 30 seconds
} as const;

export const PRODUCTION_SECURITY = {
  MAX_PARAMETER_DEPTH: 5,
  MAX_PARAMETER_COUNT: 20,
  MAX_STRING_LENGTH: 10000,
  AUDIT_LOG_RETENTION_DAYS: 90,
  SESSION_TIMEOUT_MS: 30 * 60 * 1000, // 30 minutes
  MAX_CONCURRENT_REQUESTS: 50
} as const;

export const PRODUCTION_MONITORING = {
  ERROR_RATE_THRESHOLD: 0.1, // 10%
  WARNING_RATE_THRESHOLD: 0.05, // 5%
  RESPONSE_TIME_THRESHOLD_MS: 2000,
  MEMORY_LIMIT_MB: 512,
  MEMORY_WARNING_THRESHOLD: 0.7, // 70%
  MEMORY_CRITICAL_THRESHOLD: 0.9, // 90%
  ALERT_COOLDOWN_MS: 5 * 60 * 1000 // 5 minutes
} as const;

export const PRODUCTION_RELIABILITY = {
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: 0.5, // 50%
  CIRCUIT_BREAKER_MONITORING_WINDOW_MS: 120000, // 2 minutes
  CIRCUIT_BREAKER_MINIMUM_CALLS: 5,
  RETRY_BACKOFF_MS: 1000,
  RETRY_MAX_BACKOFF_MS: 30000,
  RETRY_BACKOFF_MULTIPLIER: 2,
  TIMEOUT_DEFAULT_MS: 10000, // 10 seconds
  PERFORMANCE_OVERHEAD_LIMIT_MS: 1 // <1ms overhead requirement
} as const;